package reactive.scenarios;
// Generated 27 Jun 2021, 20:44:42 by Hibernate Tools 5.4.31.Final


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DbProperty generated by hbm2java
 */
@Entity
@Table(name="demo_table"
)
public class DbEntity  implements java.io.Serializable {


     private String name;
     private String value;
     private String description;

     @Id 
    @Column(name="name", unique=true, nullable=false, length=100)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

}


